# Generated by Django 5.0 on 2024-09-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_remove_boty_image_boty_year_alter_boty_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='boty',
            name='image',
            field=models.CharField(default='Book of the Year', max_length=100),
        ),
    ]
