# Generated by Django 5.0 on 2024-09-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_boty_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoeyawards',
            name='image',
            field=models.CharField(default='Shoey Award', max_length=100),
        ),
    ]
