# Generated by Django 5.0 on 2024-12-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_shoeyawards_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('image', models.CharField(max_length=100)),
                ('active', models.BooleanField()),
            ],
        ),
    ]
